// 20 INDIAN LANGUAGES SUPPORT

export const languages = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو' },
  { code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्' },
  { code: 'ks', name: 'Kashmiri', nativeName: 'कॉशुर' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली' },
  { code: 'sd', name: 'Sindhi', nativeName: 'سنڌي' },
  { code: 'kok', name: 'Konkani', nativeName: 'कोंकणी' },
  { code: 'mni', name: 'Manipuri', nativeName: 'মৈতৈলোন্' },
  { code: 'sat', name: 'Santali', nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ' }
]

export const translations = {
  // Navigation
  home: {
    en: 'Home',
    hi: 'होम',
    bn: 'হোম',
    te: 'హోమ్',
    mr: 'होम',
    ta: 'முகப்பு',
    gu: 'હોમ',
    kn: 'ಹೋಮ್',
    ml: 'ഹോം',
    pa: 'ਹੋਮ',
    or: 'ହୋମ୍',
    as: 'হোম',
    ur: 'ہوم',
  },
  bookTicket: {
    en: 'Book Ticket',
    hi: 'टिकट बुक करें',
    bn: 'টিকিট বুক করুন',
    te: 'టిక్కెట్ బుక్ చేయండి',
    mr: 'तिकीट बुक करा',
    ta: 'டிக்கெட் புக் செய்',
    gu: 'ટિકિટ બુક કરો',
    kn: 'ಟಿಕೆಟ್ ಬುಕ್ ಮಾಡಿ',
    ml: 'ടിക്കറ്റ് ബുക്ക് ചെയ്യുക',
    pa: 'ਟਿਕਟ ਬੁੱਕ ਕਰੋ',
    or: 'ଟିକେଟ୍ ବୁକ୍ କରନ୍ତୁ',
    as: 'টিকট বুক কৰক',
    ur: 'ٹکٹ بک کریں',
  },
  checkPNR: {
    en: 'Check PNR Status',
    hi: 'PNR स्थिति जांचें',
    bn: 'PNR স্ট্যাটাস চেক করুন',
    te: 'PNR స్థితి తనిఖీ చేయండి',
    mr: 'PNR स्थिती तपासा',
    ta: 'PNR நிலையை சரிபார்',
    gu: 'PNR સ્થિતિ તપાસો',
    kn: 'PNR ಸ್ಥಿತಿ ಪರಿಶೀಲಿಸಿ',
    ml: 'PNR സ്റ്റാറ്റസ് പരിശോധിക്കുക',
    pa: 'PNR ਸਥਿਤੀ ਜਾਂਚੋ',
    or: 'PNR ସ୍ଥିତି ଯାଞ୍ଚ କରନ୍ତୁ',
    as: 'PNR স্থিতি পৰীক্ষা কৰক',
    ur: 'PNR سٹیٹس چیک کریں',
  },
  liveStatus: {
    en: 'Live Train Status',
    hi: 'ट्रेन की वर्तमान स्थिति',
    bn: 'লাইভ ট্রেন স্ট্যাটাস',
    te: 'లైవ్ రైలు స్థితి',
    mr: 'ट्रेन लाइव्ह स्थिती',
    ta: 'லைவ் ரயில் நிலை',
    gu: 'લાઇવ ટ્રેન સ્થિતિ',
    kn: 'ಲೈವ್ ರೈಲು ಸ್ಥಿತಿ',
    ml: 'ലൈവ് ട്രെയിൻ സ്റ്റാറ്റസ്',
    pa: 'ਲਾਈਵ ਰੇਲ ਸਥਿਤੀ',
    or: 'ଲାଇଭ୍ ଟ୍ରେନ୍ ସ୍ଥିତି',
    as: 'লাইভ ট্ৰেইন স্থিতি',
    ur: 'لائیو ٹرین سٹیٹس',
  },
  seatAvailability: {
    en: 'Seat Availability',
    hi: 'सीट उपलब्धता',
    bn: 'সিট উপলব্ধতা',
    te: 'సీటు అందుబాటు',
    mr: 'सीट उपलब्धता',
    ta: 'இருக்கை கிடைக்கும் தன்மை',
    gu: 'સીટ ઉપલબ્ધતા',
    kn: 'ಸೀಟ್ ಲಭ್ಯತೆ',
    ml: 'സീറ്റ് ലഭ്യത',
    pa: 'ਸੀਟ ਉਪਲਬਧਤਾ',
    or: 'ସିଟ୍ ଉପଲବ୍ଧତା',
    as: 'আসন উপলব্ধতা',
    ur: 'سیٹ دستیابی',
  },
  fareCalculator: {
    en: 'Fare Calculator',
    hi: 'किराया कैलकुलेटर',
    bn: 'ভাড়া ক্যালকুলেটর',
    te: 'ఛార్జీల లెక్కింపు',
    mr: 'भाडे कॅल्क्युलेटर',
    ta: 'கட்டண கணிப்பான்',
    gu: 'ભાડું કેલ્ક્યુલેટર',
    kn: 'ಶುಲ್ಕ ಲೆಕ್ಕಾಚಾರ',
    ml: 'നിരക്ക് കണക്കുകൂട്ടൽ',
    pa: 'ਕਿਰਾਇਆ ਕੈਲਕੁਲੇਟਰ',
    or: 'ଭଡ଼ା କାଲ୍କୁଲେଟର',
    as: 'ভাড়া কেলকুলেটৰ',
    ur: 'کرایہ کیلکولیٹر',
  },
  from: {
    en: 'From',
    hi: 'कहाँ से',
    bn: 'কোথা থেকে',
    te: 'నుండి',
    mr: 'कुठून',
    ta: 'இருந்து',
    gu: 'ક્યાંથી',
    kn: 'ಇಂದ',
    ml: 'എവിടെ നിന്ന്',
    pa: 'ਤੋਂ',
    or: 'କେଉଁଠାରୁ',
    as: 'ক পৰা',
    ur: 'کہاں سے',
  },
  to: {
    en: 'To',
    hi: 'कहाँ तक',
    bn: 'কোথায়',
    te: 'వరకు',
    mr: 'कुठपर्यंत',
    ta: 'வரை',
    gu: 'ક્યાં સુધી',
    kn: 'ಎಲ್ಲಿಗೆ',
    ml: 'എവിടേക്ക്',
    pa: 'ਤੱਕ',
    or: 'କେଉଁଠାକୁ',
    as: 'ক লৈ',
    ur: 'کہاں تک',
  },
  search: {
    en: 'Search',
    hi: 'खोजें',
    bn: 'খুঁজুন',
    te: 'వెతకండి',
    mr: 'शोधा',
    ta: 'தேடு',
    gu: 'શોધો',
    kn: 'ಹುಡುಕಿ',
    ml: 'തിരയുക',
    pa: 'ਖੋਜੋ',
    or: 'ଖୋଜନ୍ତୁ',
    as: 'সন্ধান কৰক',
    ur: 'تلاش کریں',
  },
  cancel: {
    en: 'Cancel Ticket',
    hi: 'टिकट रद्द करें',
    bn: 'টিকিট বাতিল করুন',
    te: 'టిక్కెట్ రద్దు చేయండి',
    mr: 'तिकीट रद्द करा',
    ta: 'டிக்கெட் ரத்து செய்',
    gu: 'ટિકિટ રદ કરો',
    kn: 'ಟಿಕೆಟ್ ರದ್ದುಗೊಳಿಸಿ',
    ml: 'ടിക്കറ്റ് റദ്ദാക്കുക',
    pa: 'ਟਿਕਟ ਰੱਦ ਕਰੋ',
    or: 'ଟିକେଟ୍ ବାତିଲ୍ କରନ୍ତୁ',
    as: 'টিকট বাতিল কৰক',
    ur: 'ٹکٹ منسوخ کریں',
  },
  foodOrder: {
    en: 'Order Food',
    hi: 'खाना ऑर्डर करें',
    bn: 'খাবার অর্ডার করুন',
    te: 'ఆహారం ఆర్డర్ చేయండి',
    mr: 'अन्न ऑर्डर करा',
    ta: 'உணவு ஆர்டர் செய்',
    gu: 'ખોરાક ઓર્ડર કરો',
    kn: 'ಆಹಾರ ಆರ್ಡರ್ ಮಾಡಿ',
    ml: 'ഭക്ഷണം ഓർഡർ ചെയ്യുക',
    pa: 'ਖਾਣਾ ਆਰਡਰ ਕਰੋ',
    or: 'ଖାଦ୍ୟ ଅର୍ଡର କରନ୍ତୁ',
    as: 'খাদ্য অৰ্ডাৰ কৰক',
    ur: 'کھانا آرڈر کریں',
  },
  tatkalAlert: {
    en: 'Tatkal Alert',
    hi: 'तत्काल अलर्ट',
    bn: 'তাৎক্ষণিক সতর্কতা',
    te: 'తత్కాల హెచ్చరిక',
    mr: 'तत्काळ सूचना',
    ta: 'உடனடி எச்சரிக்கை',
    gu: 'તાત્કાલિક ચેતવણી',
    kn: 'ತಾತ್ಕಾಲಿಕ ಎಚ್ಚರಿಕೆ',
    ml: 'ടാറ്റ്കൽ അറിയിപ്പ്',
    pa: 'ਤਤਕਾਲ ਚੇਤਾਵਨੀ',
    or: 'ତାତ୍କାଲିକ ସତର୍କତା',
    as: 'তৎকাল সতৰ্কবাৰ্তা',
    ur: 'تتکال الرٹ',
  },
  voiceBooking: {
    en: 'Voice Booking',
    hi: 'आवाज़ से बुकिंग',
    bn: 'ভয়েস বুকিং',
    te: 'వాయిస్ బుకింగ్',
    mr: 'आवाज बुकिंग',
    ta: 'குரல் பதிவு',
    gu: 'વોઇસ બુકિંગ',
    kn: 'ಧ್ವನಿ ಬುಕಿಂಗ್',
    ml: 'വോയ്സ് ബുക്കിംഗ്',
    pa: 'ਅਵਾਜ਼ ਬੁਕਿੰਗ',
    or: 'ଭଏସ୍ ବୁକିଂ',
    as: 'ভইচ বুকিং',
    ur: 'آواز کی بکنگ',
  }
}

export const getTranslation = (key, lang = 'en') => {
  return translations[key]?.[lang] || translations[key]?.en || key
}
